-- ==============================================================================
-- DỰ ÁN: REMIX TRANG PHỤC TRUYỀN THỐNG VIỆT NAM
-- HỆ CƠ SỞ DỮ LIỆU POSTGRESQL TRÊN SUPABASE
-- TỔNG SỐ VẬT PHẨM: 226 (200 Trang phục cổ phong, 6 Quần, 20 Phụ kiện)
-- Hướng dẫn: Copy toàn bộ nội dung file này và dán vào Supabase SQL Editor -> bấm RUN
-- ==============================================================================

-- 1. Bật extension mở rộng cần thiết
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TẠO BẢNG clothes_items
CREATE TABLE IF NOT EXISTS public.clothes_items (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('skin', 'pants', 'accessory')),
    gender TEXT DEFAULT 'Chung',
    "colorFolder" TEXT,
    "colorName" TEXT,
    image_filename TEXT NOT NULL,
    description TEXT,
    suitable_events TEXT[] DEFAULT '{}'::text[],
    recommended_colors TEXT[] DEFAULT '{}'::text[],
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. TẠO CÁC CHỈ MỤC TỐI ƯU HIỆU NĂNG TÌM KIẾM
CREATE INDEX IF NOT EXISTS idx_clothes_items_category ON public.clothes_items(category);
CREATE INDEX IF NOT EXISTS idx_clothes_items_gender ON public.clothes_items(gender);
CREATE INDEX IF NOT EXISTS idx_clothes_items_color_folder ON public.clothes_items("colorFolder");

-- 4. CẤU HÌNH ROW LEVEL SECURITY (RLS)
ALTER TABLE public.clothes_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Cho phép đọc công khai danh mục trang phục" ON public.clothes_items;
CREATE POLICY "Cho phép đọc công khai danh mục trang phục" 
ON public.clothes_items 
FOR SELECT 
TO public 
USING (true);

DROP POLICY IF EXISTS "Cho phép chèn và cập nhật trang phục" ON public.clothes_items;
CREATE POLICY "Cho phép chèn và cập nhật trang phục" 
ON public.clothes_items 
FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

-- 5. TẠO BẢNG LƯU TRỮ LỊCH SỬ REMIX & ẢNH NGƯỜI DÙNG (saved_remixes)
CREATE TABLE IF NOT EXISTS public.saved_remixes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    filename TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    public_url TEXT NOT NULL,
    skin_id TEXT,
    pants_id TEXT,
    accessory_ids TEXT[] DEFAULT '{}'::text[],
    main_color TEXT,
    event TEXT,
    match_score NUMERIC(5, 2),
    matching_analysis TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.saved_remixes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Cho phép đọc công khai saved remixes" ON public.saved_remixes;
CREATE POLICY "Cho phép đọc công khai saved remixes" 
ON public.saved_remixes 
FOR SELECT 
TO public 
USING (true);

DROP POLICY IF EXISTS "Cho phép thêm saved remixes" ON public.saved_remixes;
CREATE POLICY "Cho phép thêm saved remixes" 
ON public.saved_remixes 
FOR INSERT 
TO public 
WITH CHECK (true);

-- 6. TẠO BUCKET STORAGE "images" VÀ PHÂN QUYỀN TRUY CẬP CÔNG KHAI
INSERT INTO storage.buckets (id, name, public) 
VALUES ('images', 'images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Read images bucket" ON storage.objects;
CREATE POLICY "Public Read images bucket" ON storage.objects
FOR SELECT TO public USING (bucket_id = 'images');

DROP POLICY IF EXISTS "Public Upload images bucket" ON storage.objects;
CREATE POLICY "Public Upload images bucket" ON storage.objects
FOR INSERT TO public WITH CHECK (bucket_id = 'images');

DROP POLICY IF EXISTS "Public Update images bucket" ON storage.objects;
CREATE POLICY "Public Update images bucket" ON storage.objects
FOR UPDATE TO public USING (bucket_id = 'images');

-- 7. TẠO BẢNG HỒ SƠ NGƯỜI DÙNG (profiles) TRÊN SUPABASE DATABASE
CREATE TABLE IF NOT EXISTS public.profiles (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE,
    email TEXT,
    full_name TEXT,
    password_hash TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Cho phép đọc công khai profiles" ON public.profiles;
CREATE POLICY "Cho phép đọc công khai profiles" ON public.profiles FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Cho phép chèn profiles" ON public.profiles;
CREATE POLICY "Cho phép chèn profiles" ON public.profiles FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "Cho phép cập nhật profiles" ON public.profiles;
CREATE POLICY "Cho phép cập nhật profiles" ON public.profiles FOR UPDATE TO public USING (true);

-- 8. CHÈN 226 VẬT PHẨM TRUYỀN THỐNG VÀO BẢNG clothes_items
INSERT INTO public.clothes_items (
    id, name, category, gender, "colorFolder", "colorName", image_filename, description, suitable_events, recommended_colors
) VALUES
('aodai_nam_xichkim_0', 'Áo Dài (Nam) - Tông Xích Kim', 'skin', 'Nam', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nam/aodai_nam_xichkim_1790751248242.jpg', 'Áo Dài thiết kế truyền thống dành cho Nam phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('aotac_nam_xichkim_1', 'Áo Tấc Ngũ Thân (Nam) - Tông Xích Kim', 'skin', 'Nam', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nam/aotac_nam_xichkim_1790752938443.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('baba_nam_xichkim_2', 'Áo Bà Ba (Nam) - Tông Xích Kim', 'skin', 'Nam', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nam/baba_nam_xichkim_1790922859519.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nam phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('cham_nam_xichkim_3', 'Trang Phục Chăm (Nam) - Tông Xích Kim', 'skin', 'Nam', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nam/cham_nam_xichkim_1790754962486.jpg', 'Trang Phục Chăm thiết kế truyền thống dành cho Nam phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('giaolinh_nam_xichkim_4', 'Áo Giao Lĩnh (Nam) - Tông Xích Kim', 'skin', 'Nam', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nam/giaolinh_nam_xichkim_1790752906819.jpg', 'Áo Giao Lĩnh thiết kế truyền thống dành cho Nam phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('mong_nam_xichkim_5', 'Trang Phục H''Mông (Nam) - Tông Xích Kim', 'skin', 'Nam', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nam/mong_nam_xichkim_1790753921678.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nam phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('nguthan_nam_xichkim_6', 'Áo Ngũ Thân (Nam) - Tông Xích Kim', 'skin', 'Nam', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nam/nguthan_nam_xichkim_1790750732187.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('quanlai_nam_xichkim_7', 'Trang Phục Quan Lại (Nam) - Tông Xích Kim', 'skin', 'Nam', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nam/quanlai_nam_xichkim_1790752925253.jpg', 'Trang Phục Quan Lại thiết kế truyền thống dành cho Nam phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('taynguyen_nam_xichkim_8', 'Trang Phục Tây Nguyên (Nam) - Tông Xích Kim', 'skin', 'Nam', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nam/taynguyen_nam_xichkim_1790921861724.jpg', 'Trang Phục Tây Nguyên thiết kế truyền thống dành cho Nam phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('tuthan_nam_xichkim_9', 'Áo Tứ Thân (Nam) - Tông Xích Kim', 'skin', 'Nam', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nam/tuthan_nam_xichkim_1790922740405.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nam phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('aobaba_nu_xichkim_0', 'Áo Bà Ba (Nữ) - Tông Xích Kim', 'skin', 'Nu', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nu/aobaba_nu_xichkim_1790760168196.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nữ phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('aocom_nu_xichkim_1', 'Áo Cắm (Nữ) - Tông Xích Kim', 'skin', 'Nu', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nu/aocom_nu_xichkim_1790757358357.jpg', 'Áo Cắm thiết kế truyền thống dành cho Nữ phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('aodai_nu_xichkim_2', 'Áo Dài (Nữ) - Tông Xích Kim', 'skin', 'Nu', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nu/aodai_nu_xichkim_1790759852241.jpg', 'Áo Dài thiết kế truyền thống dành cho Nữ phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('aonamthan_nu_xichkim_3', 'Áo Năm Thân (Nữ) - Tông Xích Kim', 'skin', 'Nu', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nu/aonamthan_nu_xichkim_1790759524622.jpg', 'Áo Năm Thân thiết kế truyền thống dành cho Nữ phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('aotac_nu_xichkim_4', 'Áo Tấc Ngũ Thân (Nữ) - Tông Xích Kim', 'skin', 'Nu', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nu/aotac_nu_xichkim_1790758895441.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('daotien_nu_xichkim_5', 'Trang Phục Dao Tiền (Nữ) - Tông Xích Kim', 'skin', 'Nu', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nu/daotien_nu_xichkim_1790760514491.jpg', 'Trang Phục Dao Tiền thiết kế truyền thống dành cho Nữ phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('hmong_nu_xichkim_6', 'Trang Phục H''Mông (Nữ) - Tông Xích Kim', 'skin', 'Nu', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nu/hmong_nu_xichkim_1790761016564.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nữ phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('nguthan_nu_xichkim_7', 'Áo Ngũ Thân (Nữ) - Tông Xích Kim', 'skin', 'Nu', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nu/nguthan_nu_xichkim_1790758491192.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('nhatbinh_nu_xichkim_8', 'Áo Nhật Bình (Nữ) - Tông Xích Kim', 'skin', 'Nu', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nu/nhatbinh_nu_xichkim_1790757699655.jpg', 'Áo Nhật Bình thiết kế truyền thống dành cho Nữ phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('tuthan_nu_xichkim_9', 'Áo Tứ Thân (Nữ) - Tông Xích Kim', 'skin', 'Nu', 'XichKim', 'Xích Kim', '/assets/images/system/Colors/XichKim/Nu/tuthan_nu_xichkim_1790759230357.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nữ phối tông màu Xích Kim quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Xích Kim"'::text[]),
('aodai_nam_bichthuy_0', 'Áo Dài (Nam) - Tông Bích Thủy', 'skin', 'Nam', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nam/aodai_nam_bichthuy_1790751261365.jpg', 'Áo Dài thiết kế truyền thống dành cho Nam phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('aotac_nam_bichthuy_1', 'Áo Tấc Ngũ Thân (Nam) - Tông Bích Thủy', 'skin', 'Nam', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nam/aotac_nam_bichthuy_1790751017950.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('baba_nam_bichthuy_2', 'Áo Bà Ba (Nam) - Tông Bích Thủy', 'skin', 'Nam', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nam/baba_nam_bichthuy_1790922120669.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nam phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('cham_nam_bichthuy_3', 'Trang Phục Chăm (Nam) - Tông Bích Thủy', 'skin', 'Nam', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nam/cham_nam_bichthuy_1790755057379.jpg', 'Trang Phục Chăm thiết kế truyền thống dành cho Nam phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('giaolinh_nam_bichthuy_4', 'Áo Giao Lĩnh (Nam) - Tông Bích Thủy', 'skin', 'Nam', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nam/giaolinh_nam_bichthuy_1790750404009.jpg', 'Áo Giao Lĩnh thiết kế truyền thống dành cho Nam phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('mong_nam_bichthuy_5', 'Trang Phục H''Mông (Nam) - Tông Bích Thủy', 'skin', 'Nam', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nam/mong_nam_bichthuy_1790754060298.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nam phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('nguthan_nam_bichthuy_6', 'Áo Ngũ Thân (Nam) - Tông Bích Thủy', 'skin', 'Nam', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nam/nguthan_nam_bichthuy_1790750747017.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('quanlai_nam_bichthuy_7', 'Trang Phục Quan Lại (Nam) - Tông Bích Thủy', 'skin', 'Nam', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nam/quanlai_nam_bichthuy_1790752076968.jpg', 'Trang Phục Quan Lại thiết kế truyền thống dành cho Nam phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('taynguyen_nam_bichthuy_8', 'Trang Phục Tây Nguyên (Nam) - Tông Bích Thủy', 'skin', 'Nam', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nam/taynguyen_nam_bichthuy_1790752358721.jpg', 'Trang Phục Tây Nguyên thiết kế truyền thống dành cho Nam phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('tuthan_nam_bichthuy_9', 'Áo Tứ Thân (Nam) - Tông Bích Thủy', 'skin', 'Nam', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nam/tuthan_nam_bichthuy_1790751797029.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nam phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('aobaba_nu_bichthuy_0', 'Áo Bà Ba (Nữ) - Tông Bích Thủy', 'skin', 'Nu', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nu/aobaba_nu_bichthuy_1790760181386.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nữ phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('aocom_nu_bichthuy_1', 'Áo Cắm (Nữ) - Tông Bích Thủy', 'skin', 'Nu', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nu/aocom_nu_bichthuy_1790757370716.jpg', 'Áo Cắm thiết kế truyền thống dành cho Nữ phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('aodai_nu_bichthuy_2', 'Áo Dài (Nữ) - Tông Bích Thủy', 'skin', 'Nu', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nu/aodai_nu_bichthuy_1790759868960.jpg', 'Áo Dài thiết kế truyền thống dành cho Nữ phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('aonamthan_nu_bichthuy_3', 'Áo Năm Thân (Nữ) - Tông Bích Thủy', 'skin', 'Nu', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nu/aonamthan_nu_bichthuy_1790759539789.jpg', 'Áo Năm Thân thiết kế truyền thống dành cho Nữ phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('aotac_nu_bichthuy_4', 'Áo Tấc Ngũ Thân (Nữ) - Tông Bích Thủy', 'skin', 'Nu', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nu/aotac_nu_bichthuy_1790758924579.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('daotien_nu_bichthuy_5', 'Trang Phục Dao Tiền (Nữ) - Tông Bích Thủy', 'skin', 'Nu', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nu/daotien_nu_bichthuy_1790760635120.jpg', 'Trang Phục Dao Tiền thiết kế truyền thống dành cho Nữ phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('hmong_nu_bichthuy_6', 'Trang Phục H''Mông (Nữ) - Tông Bích Thủy', 'skin', 'Nu', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nu/hmong_nu_bichthuy_1790761036126.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nữ phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('nguthan_nu_bichthuy_7', 'Áo Ngũ Thân (Nữ) - Tông Bích Thủy', 'skin', 'Nu', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nu/nguthan_nu_bichthuy_1790758509285.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('nhatbinh_nu_bichthuy_8', 'Áo Nhật Bình (Nữ) - Tông Bích Thủy', 'skin', 'Nu', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nu/nhatbinh_nu_bichthuy_1790757714584.jpg', 'Áo Nhật Bình thiết kế truyền thống dành cho Nữ phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('tuthan_nu_bichthuy_9', 'Áo Tứ Thân (Nữ) - Tông Bích Thủy', 'skin', 'Nu', 'BichThuy', 'Bích Thủy', '/assets/images/system/Colors/BichThuy/Nu/tuthan_nu_bichthuy_1790759244513.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nữ phối tông màu Bích Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bích Thủy"'::text[]),
('aodai_nam_huyenchu_0', 'Áo Dài (Nam) - Tông Huyền Chu', 'skin', 'Nam', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nam/aodai_nam_huyenchu_1790751274474.jpg', 'Áo Dài thiết kế truyền thống dành cho Nam phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('aotac_nam_huyenchu_1', 'Áo Tấc Ngũ Thân (Nam) - Tông Huyền Chu', 'skin', 'Nam', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nam/aotac_nam_huyenchu_1790751030747.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('baba_nam_huyenchu_2', 'Áo Bà Ba (Nam) - Tông Huyền Chu', 'skin', 'Nam', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nam/baba_nam_huyenchu_1790922674293.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nam phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('cham_nam_huyenchu_3', 'Trang Phục Chăm (Nam) - Tông Huyền Chu', 'skin', 'Nam', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nam/cham_nam_huyenchu_1790922835776.jpg', 'Trang Phục Chăm thiết kế truyền thống dành cho Nam phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('giaolinh_nam_huyenchu_4', 'Áo Giao Lĩnh (Nam) - Tông Huyền Chu', 'skin', 'Nam', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nam/giaolinh_nam_huyenchu_1790750420651.jpg', 'Áo Giao Lĩnh thiết kế truyền thống dành cho Nam phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('mong_nam_huyenchu_5', 'Trang Phục H''Mông (Nam) - Tông Huyền Chu', 'skin', 'Nam', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nam/mong_nam_huyenchu_1790754072150.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nam phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('nguthan_nam_huyenchu_6', 'Áo Ngũ Thân (Nam) - Tông Huyền Chu', 'skin', 'Nam', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nam/nguthan_nam_huyenchu_1790750759563.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('quanlai_nam_huyenchu_7', 'Trang Phục Quan Lại (Nam) - Tông Huyền Chu', 'skin', 'Nam', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nam/quanlai_nam_huyenchu_1790752091042.jpg', 'Trang Phục Quan Lại thiết kế truyền thống dành cho Nam phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('taynguyen_nam_huyenchu_8', 'Trang Phục Tây Nguyên (Nam) - Tông Huyền Chu', 'skin', 'Nam', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nam/taynguyen_nam_huyenchu_1790752372232.jpg', 'Trang Phục Tây Nguyên thiết kế truyền thống dành cho Nam phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('tuthan_nam_huyenchu_9', 'Áo Tứ Thân (Nam) - Tông Huyền Chu', 'skin', 'Nam', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nam/tuthan_nam_huyenchu_1790922795079.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nam phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('aobaba_nu_huyenchu_0', 'Áo Bà Ba (Nữ) - Tông Huyền Chu', 'skin', 'Nu', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nu/aobaba_nu_huyenchu_1790760194694.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nữ phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('aocom_nu_huyenchu_1', 'Áo Cắm (Nữ) - Tông Huyền Chu', 'skin', 'Nu', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nu/aocom_nu_huyenchu_1790757381566.jpg', 'Áo Cắm thiết kế truyền thống dành cho Nữ phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('aodai_nu_huyenchu_2', 'Áo Dài (Nữ) - Tông Huyền Chu', 'skin', 'Nu', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nu/aodai_nu_huyenchu_1790759882685.jpg', 'Áo Dài thiết kế truyền thống dành cho Nữ phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('aonamthan_nu_huyenchu_3', 'Áo Năm Thân (Nữ) - Tông Huyền Chu', 'skin', 'Nu', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nu/aonamthan_nu_huyenchu_1790759551995.jpg', 'Áo Năm Thân thiết kế truyền thống dành cho Nữ phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('aotac_nu_huyenchu_4', 'Áo Tấc Ngũ Thân (Nữ) - Tông Huyền Chu', 'skin', 'Nu', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nu/aotac_nu_huyenchu_1790758939274.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('daotien_nu_huyenchu_5', 'Trang Phục Dao Tiền (Nữ) - Tông Huyền Chu', 'skin', 'Nu', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nu/daotien_nu_huyenchu_1790760528167.jpg', 'Trang Phục Dao Tiền thiết kế truyền thống dành cho Nữ phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('hmong_nu_huyenchu_6', 'Trang Phục H''Mông (Nữ) - Tông Huyền Chu', 'skin', 'Nu', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nu/hmong_nu_huyenchu_1790761052748.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nữ phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('nguthan_nu_huyenchu_7', 'Áo Ngũ Thân (Nữ) - Tông Huyền Chu', 'skin', 'Nu', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nu/nguthan_nu_huyenchu_1790758526470.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('nhatbinh_nu_huyenchu_8', 'Áo Nhật Bình (Nữ) - Tông Huyền Chu', 'skin', 'Nu', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nu/nhatbinh_nu_huyenchu_1790757728416.jpg', 'Áo Nhật Bình thiết kế truyền thống dành cho Nữ phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('tuthan_nu_huyenchu_9', 'Áo Tứ Thân (Nữ) - Tông Huyền Chu', 'skin', 'Nu', 'HuyenChu', 'Huyền Chu', '/assets/images/system/Colors/HuyenChu/Nu/tuthan_nu_huyenchu_1790759256588.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nữ phối tông màu Huyền Chu quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Huyền Chu"'::text[]),
('aodai_nam_thanhlam_0', 'Áo Dài (Nam) - Tông Thanh Lam', 'skin', 'Nam', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nam/aodai_nam_thanhlam_1790751287221.jpg', 'Áo Dài thiết kế truyền thống dành cho Nam phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('aotac_nam_thanhlam_1', 'Áo Tấc Ngũ Thân (Nam) - Tông Thanh Lam', 'skin', 'Nam', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nam/aotac_nam_thanhlam_1790751041688.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('baba_nam_thanhlam_2', 'Áo Bà Ba (Nam) - Tông Thanh Lam', 'skin', 'Nam', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nam/baba_nam_thanhlam_1790751567430.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nam phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('cham_nam_thanhlam_3', 'Trang Phục Chăm (Nam) - Tông Thanh Lam', 'skin', 'Nam', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nam/cham_nam_thanhlam_1790755086362.jpg', 'Trang Phục Chăm thiết kế truyền thống dành cho Nam phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('giaolinh_nam_thanhlam_4', 'Áo Giao Lĩnh (Nam) - Tông Thanh Lam', 'skin', 'Nam', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nam/giaolinh_nam_thanhlam_1790750435231.jpg', 'Áo Giao Lĩnh thiết kế truyền thống dành cho Nam phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('mong_nam_thanhlam_5', 'Trang Phục H''Mông (Nam) - Tông Thanh Lam', 'skin', 'Nam', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nam/mong_nam_thanhlam_1790754085722.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nam phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('nguthan_nam_thanhlam_6', 'Áo Ngũ Thân (Nam) - Tông Thanh Lam', 'skin', 'Nam', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nam/nguthan_nam_thanhlam_1790750769077.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('quanlai_nam_thanhlam_7', 'Trang Phục Quan Lại (Nam) - Tông Thanh Lam', 'skin', 'Nam', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nam/quanlai_nam_thanhlam_1790752106203.jpg', 'Trang Phục Quan Lại thiết kế truyền thống dành cho Nam phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('taynguyen_nam_thanhlam_8', 'Trang Phục Tây Nguyên (Nam) - Tông Thanh Lam', 'skin', 'Nam', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nam/taynguyen_nam_thanhlam_1790752386693.jpg', 'Trang Phục Tây Nguyên thiết kế truyền thống dành cho Nam phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('tuthan_nam_thanhlam_9', 'Áo Tứ Thân (Nam) - Tông Thanh Lam', 'skin', 'Nam', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nam/tuthan_nam_thanhlam_1790751827538.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nam phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('aobaba_nu_thanhlam_0', 'Áo Bà Ba (Nữ) - Tông Thanh Lam', 'skin', 'Nu', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nu/aobaba_nu_thanhlam_1790760207297.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nữ phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('aocom_nu_thanhlam_1', 'Áo Cắm (Nữ) - Tông Thanh Lam', 'skin', 'Nu', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nu/aocom_nu_thanhlam_1790757392586.jpg', 'Áo Cắm thiết kế truyền thống dành cho Nữ phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('aodai_nu_thanhlam_2', 'Áo Dài (Nữ) - Tông Thanh Lam', 'skin', 'Nu', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nu/aodai_nu_thanhlam_1790759899088.jpg', 'Áo Dài thiết kế truyền thống dành cho Nữ phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('aonamthan_nu_thanhlam_3', 'Áo Năm Thân (Nữ) - Tông Thanh Lam', 'skin', 'Nu', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nu/aonamthan_nu_thanhlam_1790759563440.jpg', 'Áo Năm Thân thiết kế truyền thống dành cho Nữ phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('aotac_nu_thanhlam_4', 'Áo Tấc Ngũ Thân (Nữ) - Tông Thanh Lam', 'skin', 'Nu', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nu/aotac_nu_thanhlam_1790758959400.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('daotien_nu_thanhlam_5', 'Trang Phục Dao Tiền (Nữ) - Tông Thanh Lam', 'skin', 'Nu', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nu/daotien_nu_thanhlam_1790760542424.jpg', 'Trang Phục Dao Tiền thiết kế truyền thống dành cho Nữ phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('hmong_nu_thanhlam_6', 'Trang Phục H''Mông (Nữ) - Tông Thanh Lam', 'skin', 'Nu', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nu/hmong_nu_thanhlam_1790761065665.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nữ phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('nguthan_nu_thanhlam_7', 'Áo Ngũ Thân (Nữ) - Tông Thanh Lam', 'skin', 'Nu', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nu/nguthan_nu_thanhlam_1790758541294.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('nhatbinh_nu_thanhlam_8', 'Áo Nhật Bình (Nữ) - Tông Thanh Lam', 'skin', 'Nu', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nu/nhatbinh_nu_thanhlam_1790757740836.jpg', 'Áo Nhật Bình thiết kế truyền thống dành cho Nữ phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('tuthan_nu_thanhlam_9', 'Áo Tứ Thân (Nữ) - Tông Thanh Lam', 'skin', 'Nu', 'ThanhLam', 'Thanh Lam', '/assets/images/system/Colors/ThanhLam/Nu/tuthan_nu_thanhlam_1790759268328.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nữ phối tông màu Thanh Lam quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thanh Lam"'::text[]),
('aodai_nam_hoangyen_0', 'Áo Dài (Nam) - Tông Hoàng Yến', 'skin', 'Nam', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nam/aodai_nam_hoangyen_1790751299046.jpg', 'Áo Dài thiết kế truyền thống dành cho Nam phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('aotac_nam_hoangyen_1', 'Áo Tấc Ngũ Thân (Nam) - Tông Hoàng Yến', 'skin', 'Nam', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nam/aotac_nam_hoangyen_1790751053983.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('baba_nam_hoangyen_2', 'Áo Bà Ba (Nam) - Tông Hoàng Yến', 'skin', 'Nam', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nam/baba_nam_hoangyen_1790751578799.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nam phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('cham_nam_hoangyen_3', 'Trang Phục Chăm (Nam) - Tông Hoàng Yến', 'skin', 'Nam', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nam/cham_nam_hoangyen_1790754981786.jpg', 'Trang Phục Chăm thiết kế truyền thống dành cho Nam phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('giaolinh_nam_hoangyen_4', 'Áo Giao Lĩnh (Nam) - Tông Hoàng Yến', 'skin', 'Nam', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nam/giaolinh_nam_hoangyen_1790750450202.jpg', 'Áo Giao Lĩnh thiết kế truyền thống dành cho Nam phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('mong_nam_hoangyen_5', 'Trang Phục H''Mông (Nam) - Tông Hoàng Yến', 'skin', 'Nam', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nam/mong_nam_hoangyen_1790754097875.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nam phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('nguthan_nam_hoangyen_6', 'Áo Ngũ Thân (Nam) - Tông Hoàng Yến', 'skin', 'Nam', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nam/nguthan_nam_hoangyen_1790750781006.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('quanlai_nam_hoangyen_7', 'Trang Phục Quan Lại (Nam) - Tông Hoàng Yến', 'skin', 'Nam', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nam/quanlai_nam_hoangyen_1790752124725.jpg', 'Trang Phục Quan Lại thiết kế truyền thống dành cho Nam phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('taynguyen_nam_hoangyen_8', 'Trang Phục Tây Nguyên (Nam) - Tông Hoàng Yến', 'skin', 'Nam', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nam/taynguyen_nam_hoangyen_1790752398271.jpg', 'Trang Phục Tây Nguyên thiết kế truyền thống dành cho Nam phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('tuthan_nam_hoangyen_9', 'Áo Tứ Thân (Nam) - Tông Hoàng Yến', 'skin', 'Nam', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nam/tuthan_nam_hoangyen_1790751840293.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nam phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('aobaba_nu_hoangyen_0', 'Áo Bà Ba (Nữ) - Tông Hoàng Yến', 'skin', 'Nu', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nu/aobaba_nu_hoangyen_1790760218750.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nữ phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('aocom_nu_hoangyen_1', 'Áo Cắm (Nữ) - Tông Hoàng Yến', 'skin', 'Nu', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nu/aocom_nu_hoangyen_1790757406098.jpg', 'Áo Cắm thiết kế truyền thống dành cho Nữ phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('aodai_nu_hoangyen_2', 'Áo Dài (Nữ) - Tông Hoàng Yến', 'skin', 'Nu', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nu/aodai_nu_hoangyen_1790759912216.jpg', 'Áo Dài thiết kế truyền thống dành cho Nữ phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('aonamthan_nu_hoangyen_3', 'Áo Năm Thân (Nữ) - Tông Hoàng Yến', 'skin', 'Nu', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nu/aonamthan_nu_hoangyen_1790759575472.jpg', 'Áo Năm Thân thiết kế truyền thống dành cho Nữ phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('aotac_nu_hoangyen_4', 'Áo Tấc Ngũ Thân (Nữ) - Tông Hoàng Yến', 'skin', 'Nu', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nu/aotac_nu_hoangyen_1790758979062.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('daotien_nu_hoangyen_5', 'Trang Phục Dao Tiền (Nữ) - Tông Hoàng Yến', 'skin', 'Nu', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nu/daotien_nu_hoangyen_1790760553477.jpg', 'Trang Phục Dao Tiền thiết kế truyền thống dành cho Nữ phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('hmong_nu_hoangyen_6', 'Trang Phục H''Mông (Nữ) - Tông Hoàng Yến', 'skin', 'Nu', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nu/hmong_nu_hoangyen_1790761079526.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nữ phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('nguthan_nu_hoangyen_7', 'Áo Ngũ Thân (Nữ) - Tông Hoàng Yến', 'skin', 'Nu', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nu/nguthan_nu_hoangyen_1790758553615.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('nhatbinh_nu_hoangyen_8', 'Áo Nhật Bình (Nữ) - Tông Hoàng Yến', 'skin', 'Nu', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nu/nhatbinh_nu_hoangyen_1790757754540.jpg', 'Áo Nhật Bình thiết kế truyền thống dành cho Nữ phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('tuthan_nu_hoangyen_9', 'Áo Tứ Thân (Nữ) - Tông Hoàng Yến', 'skin', 'Nu', 'HoangYen', 'Hoàng Yến', '/assets/images/system/Colors/HoangYen/Nu/tuthan_nu_hoangyen_1790759280134.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nữ phối tông màu Hoàng Yến quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Hoàng Yến"'::text[]),
('aodai_nam_bachngoc_0', 'Áo Dài (Nam) - Tông Bạch Ngọc', 'skin', 'Nam', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nam/aodai_nam_bachngoc_1790751309823.jpg', 'Áo Dài thiết kế truyền thống dành cho Nam phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('aotac_nam_bachngoc_1', 'Áo Tấc Ngũ Thân (Nam) - Tông Bạch Ngọc', 'skin', 'Nam', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nam/aotac_nam_bachngoc_1790751065080.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('baba_nam_bachngoc_2', 'Áo Bà Ba (Nam) - Tông Bạch Ngọc', 'skin', 'Nam', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nam/baba_nam_bachngoc_1790751590309.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nam phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('cham_nam_bachngoc_3', 'Trang Phục Chăm (Nam) - Tông Bạch Ngọc', 'skin', 'Nam', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nam/cham_nam_bachngoc_1790754994113.jpg', 'Trang Phục Chăm thiết kế truyền thống dành cho Nam phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('giaolinh_nam_bachngoc_4', 'Áo Giao Lĩnh (Nam) - Tông Bạch Ngọc', 'skin', 'Nam', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nam/giaolinh_nam_bachngoc_1790750467887.jpg', 'Áo Giao Lĩnh thiết kế truyền thống dành cho Nam phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('mong_nam_bachngoc_5', 'Trang Phục H''Mông (Nam) - Tông Bạch Ngọc', 'skin', 'Nam', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nam/mong_nam_bachngoc_1790754109732.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nam phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('nguthan_nam_bachngoc_6', 'Áo Ngũ Thân (Nam) - Tông Bạch Ngọc', 'skin', 'Nam', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nam/nguthan_nam_bachngoc_1790750794157.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('quanlai_nam_bachngoc_7', 'Trang Phục Quan Lại (Nam) - Tông Bạch Ngọc', 'skin', 'Nam', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nam/quanlai_nam_bachngoc_1790752136686.jpg', 'Trang Phục Quan Lại thiết kế truyền thống dành cho Nam phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('taynguyen_nam_bachngoc_8', 'Trang Phục Tây Nguyên (Nam) - Tông Bạch Ngọc', 'skin', 'Nam', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nam/taynguyen_nam_bachngoc_1790752409408.jpg', 'Trang Phục Tây Nguyên thiết kế truyền thống dành cho Nam phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('tuthan_nam_bachngoc_9', 'Áo Tứ Thân (Nam) - Tông Bạch Ngọc', 'skin', 'Nam', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nam/tuthan_nam_bachngoc_1790751853641.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nam phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('aobaba_nu_bachngoc_0', 'Áo Bà Ba (Nữ) - Tông Bạch Ngọc', 'skin', 'Nu', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nu/aobaba_nu_bachngoc_1790760237310.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nữ phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('aocom_nu_bachngoc_1', 'Áo Cắm (Nữ) - Tông Bạch Ngọc', 'skin', 'Nu', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nu/aocom_nu_bachngoc_1790757417401.jpg', 'Áo Cắm thiết kế truyền thống dành cho Nữ phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('aodai_nu_bachngoc_2', 'Áo Dài (Nữ) - Tông Bạch Ngọc', 'skin', 'Nu', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nu/aodai_nu_bachngoc_1790759924645.jpg', 'Áo Dài thiết kế truyền thống dành cho Nữ phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('aonamthan_nu_bachngoc_3', 'Áo Năm Thân (Nữ) - Tông Bạch Ngọc', 'skin', 'Nu', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nu/aonamthan_nu_bachngoc_1790759586229.jpg', 'Áo Năm Thân thiết kế truyền thống dành cho Nữ phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('aotac_nu_bachngoc_4', 'Áo Tấc Ngũ Thân (Nữ) - Tông Bạch Ngọc', 'skin', 'Nu', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nu/aotac_nu_bachngoc_1790758993429.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('daotien_nu_bachngoc_5', 'Trang Phục Dao Tiền (Nữ) - Tông Bạch Ngọc', 'skin', 'Nu', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nu/daotien_nu_bachngoc_1790874966539.jpg', 'Trang Phục Dao Tiền thiết kế truyền thống dành cho Nữ phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('hmong_nu_bachngoc_6', 'Trang Phục H''Mông (Nữ) - Tông Bạch Ngọc', 'skin', 'Nu', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nu/hmong_nu_bachngoc_1790761098962.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nữ phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('nguthan_nu_bachngoc_7', 'Áo Ngũ Thân (Nữ) - Tông Bạch Ngọc', 'skin', 'Nu', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nu/nguthan_nu_bachngoc_1790758569548.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('nhatbinh_nu_bachngoc_8', 'Áo Nhật Bình (Nữ) - Tông Bạch Ngọc', 'skin', 'Nu', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nu/nhatbinh_nu_bachngoc_1790757772939.jpg', 'Áo Nhật Bình thiết kế truyền thống dành cho Nữ phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('tuthan_nu_bachngoc_9', 'Áo Tứ Thân (Nữ) - Tông Bạch Ngọc', 'skin', 'Nu', 'BachNgoc', 'Bạch Ngọc', '/assets/images/system/Colors/BachNgoc/Nu/tuthan_nu_bachngoc_1790759292866.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nữ phối tông màu Bạch Ngọc quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Bạch Ngọc"'::text[]),
('aodai_nam_tukhi_0', 'Áo Dài (Nam) - Tông Tử Khí', 'skin', 'Nam', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nam/aodai_nam_tukhi_1790751322160.jpg', 'Áo Dài thiết kế truyền thống dành cho Nam phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('aotac_nam_tukhi_1', 'Áo Tấc Ngũ Thân (Nam) - Tông Tử Khí', 'skin', 'Nam', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nam/aotac_nam_tukhi_1790751076280.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('baba_nam_tukhi_2', 'Áo Bà Ba (Nam) - Tông Tử Khí', 'skin', 'Nam', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nam/baba_nam_tukhi_1790751602354.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nam phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('cham_nam_tukhi_3', 'Trang Phục Chăm (Nam) - Tông Tử Khí', 'skin', 'Nam', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nam/cham_nam_tukhi_1790758158575.jpg', 'Trang Phục Chăm thiết kế truyền thống dành cho Nam phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('giaolinh_nam_tukhi_4', 'Áo Giao Lĩnh (Nam) - Tông Tử Khí', 'skin', 'Nam', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nam/giaolinh_nam_tukhi_1790750482639.jpg', 'Áo Giao Lĩnh thiết kế truyền thống dành cho Nam phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('mong_nam_tukhi_5', 'Trang Phục H''Mông (Nam) - Tông Tử Khí', 'skin', 'Nam', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nam/mong_nam_tukhi_1790754121843.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nam phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('nguthan_nam_tukhi_6', 'Áo Ngũ Thân (Nam) - Tông Tử Khí', 'skin', 'Nam', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nam/nguthan_nam_tukhi_1790750806423.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('quanlai_nam_tukhi_7', 'Trang Phục Quan Lại (Nam) - Tông Tử Khí', 'skin', 'Nam', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nam/quanlai_nam_tukhi_1790752151434.jpg', 'Trang Phục Quan Lại thiết kế truyền thống dành cho Nam phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('taynguyen_nam_tukhi_8', 'Trang Phục Tây Nguyên (Nam) - Tông Tử Khí', 'skin', 'Nam', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nam/taynguyen_nam_tukhi_1790752423433.jpg', 'Trang Phục Tây Nguyên thiết kế truyền thống dành cho Nam phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('tuthan_nam_tukhi_9', 'Áo Tứ Thân (Nam) - Tông Tử Khí', 'skin', 'Nam', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nam/tuthan_nam_tukhi_1790751868041.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nam phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('aobaba_nu_tukhi_0', 'Áo Bà Ba (Nữ) - Tông Tử Khí', 'skin', 'Nu', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nu/aobaba_nu_tukhi_1790760262982.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nữ phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('aocom_nu_tukhi_1', 'Áo Cắm (Nữ) - Tông Tử Khí', 'skin', 'Nu', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nu/aocom_nu_tukhi_1790757428642.jpg', 'Áo Cắm thiết kế truyền thống dành cho Nữ phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('aodai_nu_tukhi_2', 'Áo Dài (Nữ) - Tông Tử Khí', 'skin', 'Nu', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nu/aodai_nu_tukhi_1790759942580.jpg', 'Áo Dài thiết kế truyền thống dành cho Nữ phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('aonamthan_nu_tukhi_3', 'Áo Năm Thân (Nữ) - Tông Tử Khí', 'skin', 'Nu', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nu/aonamthan_nu_tukhi_1790759638582.jpg', 'Áo Năm Thân thiết kế truyền thống dành cho Nữ phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('aotac_nu_tukhi_4', 'Áo Tấc Ngũ Thân (Nữ) - Tông Tử Khí', 'skin', 'Nu', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nu/aotac_nu_tukhi_1790759013061.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('daotien_nu_tukhi_5', 'Trang Phục Dao Tiền (Nữ) - Tông Tử Khí', 'skin', 'Nu', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nu/daotien_nu_tukhi_1790921372380.jpg', 'Trang Phục Dao Tiền thiết kế truyền thống dành cho Nữ phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('hmong_nu_tukhi_6', 'Trang Phục H''Mông (Nữ) - Tông Tử Khí', 'skin', 'Nu', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nu/hmong_nu_tukhi_1790761114485.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nữ phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('nguthan_nu_tukhi_7', 'Áo Ngũ Thân (Nữ) - Tông Tử Khí', 'skin', 'Nu', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nu/nguthan_nu_tukhi_1790758583886.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('nhatbinh_nu_tukhi_8', 'Áo Nhật Bình (Nữ) - Tông Tử Khí', 'skin', 'Nu', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nu/nhatbinh_nu_tukhi_1790757798619.jpg', 'Áo Nhật Bình thiết kế truyền thống dành cho Nữ phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('tuthan_nu_tukhi_9', 'Áo Tứ Thân (Nữ) - Tông Tử Khí', 'skin', 'Nu', 'TuKhi', 'Tử Khí', '/assets/images/system/Colors/TuKhi/Nu/tuthan_nu_tukhi_1790759302154.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nữ phối tông màu Tử Khí quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Tử Khí"'::text[]),
('aodai_nam_phithuy_0', 'Áo Dài (Nam) - Tông Phi Thủy', 'skin', 'Nam', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nam/aodai_nam_phithuy_1790751335399.jpg', 'Áo Dài thiết kế truyền thống dành cho Nam phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('aotac_nam_phithuy_1', 'Áo Tấc Ngũ Thân (Nam) - Tông Phi Thủy', 'skin', 'Nam', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nam/aotac_nam_phithuy_1790751088255.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('baba_nam_phithuy_2', 'Áo Bà Ba (Nam) - Tông Phi Thủy', 'skin', 'Nam', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nam/baba_nam_phithuy_1790922700552.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nam phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('cham_nam_phithuy_3', 'Trang Phục Chăm (Nam) - Tông Phi Thủy', 'skin', 'Nam', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nam/cham_nam_phithuy_1790755017151.jpg', 'Trang Phục Chăm thiết kế truyền thống dành cho Nam phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('giaolinh_nam_phithuy_4', 'Áo Giao Lĩnh (Nam) - Tông Phi Thủy', 'skin', 'Nam', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nam/giaolinh_nam_phithuy_1790750503282.jpg', 'Áo Giao Lĩnh thiết kế truyền thống dành cho Nam phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('mong_nam_phithuy_5', 'Trang Phục H''Mông (Nam) - Tông Phi Thủy', 'skin', 'Nam', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nam/mong_nam_phithuy_1790754488206.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nam phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('nguthan_nam_phithuy_6', 'Áo Ngũ Thân (Nam) - Tông Phi Thủy', 'skin', 'Nam', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nam/nguthan_nam_phithuy_1790750818032.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('quanlai_nam_phithuy_7', 'Trang Phục Quan Lại (Nam) - Tông Phi Thủy', 'skin', 'Nam', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nam/quanlai_nam_phithuy_1790752163467.jpg', 'Trang Phục Quan Lại thiết kế truyền thống dành cho Nam phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('taynguyen_nam_phithuy_8', 'Trang Phục Tây Nguyên (Nam) - Tông Phi Thủy', 'skin', 'Nam', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nam/taynguyen_nam_phithuy_1790752435388.jpg', 'Trang Phục Tây Nguyên thiết kế truyền thống dành cho Nam phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('tuthan_nam_phithuy_9', 'Áo Tứ Thân (Nam) - Tông Phi Thủy', 'skin', 'Nam', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nam/tuthan_nam_phithuy_1790751884201.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nam phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('aobaba_nu_phithuy_0', 'Áo Bà Ba (Nữ) - Tông Phi Thủy', 'skin', 'Nu', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nu/aobaba_nu_phithuy_1790760279513.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nữ phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('aocom_nu_phithuy_1', 'Áo Cắm (Nữ) - Tông Phi Thủy', 'skin', 'Nu', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nu/aocom_nu_phithuy_1790757441290.jpg', 'Áo Cắm thiết kế truyền thống dành cho Nữ phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('aodai_nu_phithuy_2', 'Áo Dài (Nữ) - Tông Phi Thủy', 'skin', 'Nu', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nu/aodai_nu_phithuy_1790759958356.jpg', 'Áo Dài thiết kế truyền thống dành cho Nữ phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('aonamthan_nu_phithuy_3', 'Áo Năm Thân (Nữ) - Tông Phi Thủy', 'skin', 'Nu', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nu/aonamthan_nu_phithuy_1790759600268.jpg', 'Áo Năm Thân thiết kế truyền thống dành cho Nữ phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('aotac_nu_phithuy_4', 'Áo Tấc Ngũ Thân (Nữ) - Tông Phi Thủy', 'skin', 'Nu', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nu/aotac_nu_phithuy_1790759029394.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('daotien_nu_phithuy_5', 'Trang Phục Dao Tiền (Nữ) - Tông Phi Thủy', 'skin', 'Nu', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nu/daotien_nu_phithuy_1790760589944.jpg', 'Trang Phục Dao Tiền thiết kế truyền thống dành cho Nữ phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('hmong_nu_phithuy_6', 'Trang Phục H''Mông (Nữ) - Tông Phi Thủy', 'skin', 'Nu', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nu/hmong_nu_phithuy_1790761128978.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nữ phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('nguthan_nu_phithuy_7', 'Áo Ngũ Thân (Nữ) - Tông Phi Thủy', 'skin', 'Nu', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nu/nguthan_nu_phithuy_1790758602146.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('nhatbinh_nu_phithuy_8', 'Áo Nhật Bình (Nữ) - Tông Phi Thủy', 'skin', 'Nu', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nu/nhatbinh_nu_phithuy_1790757810793.jpg', 'Áo Nhật Bình thiết kế truyền thống dành cho Nữ phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('tuthan_nu_phithuy_9', 'Áo Tứ Thân (Nữ) - Tông Phi Thủy', 'skin', 'Nu', 'PhiThuy', 'Phi Thủy', '/assets/images/system/Colors/PhiThuy/Nu/tuthan_nu_phithuy_1790759313464.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nữ phối tông màu Phi Thủy quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Phi Thủy"'::text[]),
('aodai_nam_thohoang_0', 'Áo Dài (Nam) - Tông Thổ Hoàng', 'skin', 'Nam', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nam/aodai_nam_thohoang_1790751346864.jpg', 'Áo Dài thiết kế truyền thống dành cho Nam phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('aotac_nam_thohoang_1', 'Áo Tấc Ngũ Thân (Nam) - Tông Thổ Hoàng', 'skin', 'Nam', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nam/aotac_nam_thohoang_1790753569028.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('baba_nam_thohoang_2', 'Áo Bà Ba (Nam) - Tông Thổ Hoàng', 'skin', 'Nam', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nam/baba_nam_thohoang_1790922719656.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nam phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('cham_nam_thohoang_3', 'Trang Phục Chăm (Nam) - Tông Thổ Hoàng', 'skin', 'Nam', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nam/cham_nam_thohoang_1790755026998.jpg', 'Trang Phục Chăm thiết kế truyền thống dành cho Nam phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('giaolinh_nam_thohoang_4', 'Áo Giao Lĩnh (Nam) - Tông Thổ Hoàng', 'skin', 'Nam', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nam/giaolinh_nam_thohoang_1790750520142.jpg', 'Áo Giao Lĩnh thiết kế truyền thống dành cho Nam phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('mong_nam_thohoang_5', 'Trang Phục H''Mông (Nam) - Tông Thổ Hoàng', 'skin', 'Nam', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nam/mong_nam_thohoang_1790754135352.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nam phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('nguthan_nam_thohoang_6', 'Áo Ngũ Thân (Nam) - Tông Thổ Hoàng', 'skin', 'Nam', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nam/nguthan_nam_thohoang_1790750832134.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('quanlai_nam_thohoang_7', 'Trang Phục Quan Lại (Nam) - Tông Thổ Hoàng', 'skin', 'Nam', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nam/quanlai_nam_thohoang_1790752175898.jpg', 'Trang Phục Quan Lại thiết kế truyền thống dành cho Nam phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('taynguyen_nam_thohoang_8', 'Trang Phục Tây Nguyên (Nam) - Tông Thổ Hoàng', 'skin', 'Nam', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nam/taynguyen_nam_thohoang_1790752447101.jpg', 'Trang Phục Tây Nguyên thiết kế truyền thống dành cho Nam phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('tuthan_nam_thohoang_9', 'Áo Tứ Thân (Nam) - Tông Thổ Hoàng', 'skin', 'Nam', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nam/tuthan_nam_thohoang_1790751896786.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nam phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('aobaba_nu_thohoang_0', 'Áo Bà Ba (Nữ) - Tông Thổ Hoàng', 'skin', 'Nu', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nu/aobaba_nu_thohoang_1790760313010.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nữ phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('aocom_nu_thohoang_1', 'Áo Cắm (Nữ) - Tông Thổ Hoàng', 'skin', 'Nu', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nu/aocom_nu_thohoang_1790757451935.jpg', 'Áo Cắm thiết kế truyền thống dành cho Nữ phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('aodai_nu_thohoang_2', 'Áo Dài (Nữ) - Tông Thổ Hoàng', 'skin', 'Nu', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nu/aodai_nu_thohoang_1790759975714.jpg', 'Áo Dài thiết kế truyền thống dành cho Nữ phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('aonamthan_nu_thohoang_3', 'Áo Năm Thân (Nữ) - Tông Thổ Hoàng', 'skin', 'Nu', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nu/aonamthan_nu_thohoang_1790759613041.jpg', 'Áo Năm Thân thiết kế truyền thống dành cho Nữ phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('aotac_nu_thohoang_4', 'Áo Tấc Ngũ Thân (Nữ) - Tông Thổ Hoàng', 'skin', 'Nu', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nu/aotac_nu_thohoang_1790759046736.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('daotien_nu_thohoang_5', 'Trang Phục Dao Tiền (Nữ) - Tông Thổ Hoàng', 'skin', 'Nu', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nu/daotien_nu_thohoang_1790760602714.jpg', 'Trang Phục Dao Tiền thiết kế truyền thống dành cho Nữ phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('hmong_nu_thohoang_6', 'Trang Phục H''Mông (Nữ) - Tông Thổ Hoàng', 'skin', 'Nu', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nu/hmong_nu_thohoang_1790761142759.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nữ phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('nguthan_nu_thohoang_7', 'Áo Ngũ Thân (Nữ) - Tông Thổ Hoàng', 'skin', 'Nu', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nu/nguthan_nu_thohoang_1790758615991.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('nhatbinh_nu_thohoang_8', 'Áo Nhật Bình (Nữ) - Tông Thổ Hoàng', 'skin', 'Nu', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nu/nhatbinh_nu_thohoang_1790757825662.jpg', 'Áo Nhật Bình thiết kế truyền thống dành cho Nữ phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('tuthan_nu_thohoang_9', 'Áo Tứ Thân (Nữ) - Tông Thổ Hoàng', 'skin', 'Nu', 'ThoHoang', 'Thổ Hoàng', '/assets/images/system/Colors/ThoHoang/Nu/tuthan_nu_thohoang_1790759324934.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nữ phối tông màu Thổ Hoàng quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Thổ Hoàng"'::text[]),
('aodai_nam_lienhoa_0', 'Áo Dài (Nam) - Tông Liên Hoa', 'skin', 'Nam', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nam/aodai_nam_lienhoa_1790753248784.jpg', 'Áo Dài thiết kế truyền thống dành cho Nam phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('aotac_nam_lienhoa_1', 'Áo Tấc Ngũ Thân (Nam) - Tông Liên Hoa', 'skin', 'Nam', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nam/aotac_nam_lienhoa_1790753592501.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('baba_nam_lienhoa_2', 'Áo Bà Ba (Nam) - Tông Liên Hoa', 'skin', 'Nam', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nam/baba_nam_lienhoa_1790753321668.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nam phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('cham_nam_lienhoa_3', 'Trang Phục Chăm (Nam) - Tông Liên Hoa', 'skin', 'Nam', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nam/cham_nam_lienhoa_1790758171596.jpg', 'Trang Phục Chăm thiết kế truyền thống dành cho Nam phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('giaolinh_nam_lienhoa_4', 'Áo Giao Lĩnh (Nam) - Tông Liên Hoa', 'skin', 'Nam', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nam/giaolinh_nam_lienhoa_1790753204357.jpg', 'Áo Giao Lĩnh thiết kế truyền thống dành cho Nam phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('mong_nam_lienhoa_5', 'Trang Phục H''Mông (Nam) - Tông Liên Hoa', 'skin', 'Nam', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nam/mong_nam_lienhoa_1790754149507.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nam phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('nguthan_nam_lienhoa_6', 'Áo Ngũ Thân (Nam) - Tông Liên Hoa', 'skin', 'Nam', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nam/nguthan_nam_lienhoa_1790753220364.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nam phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('quanlai_nam_lienhoa_7', 'Trang Phục Quan Lại (Nam) - Tông Liên Hoa', 'skin', 'Nam', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nam/quanlai_nam_lienhoa_1790753280909.jpg', 'Trang Phục Quan Lại thiết kế truyền thống dành cho Nam phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('taynguyen_nam_lienhoa_8', 'Trang Phục Tây Nguyên (Nam) - Tông Liên Hoa', 'skin', 'Nam', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nam/taynguyen_nam_lienhoa_1790753297524.jpg', 'Trang Phục Tây Nguyên thiết kế truyền thống dành cho Nam phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('tuthan_nam_lienhoa_9', 'Áo Tứ Thân (Nam) - Tông Liên Hoa', 'skin', 'Nam', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nam/tuthan_nam_lienhoa_1790753266612.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nam phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('aobaba_nu_lienhoa_0', 'Áo Bà Ba (Nữ) - Tông Liên Hoa', 'skin', 'Nu', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nu/aobaba_nu_lienhoa_1790760297922.jpg', 'Áo Bà Ba thiết kế truyền thống dành cho Nữ phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('aocom_nu_lienhoa_1', 'Áo Cắm (Nữ) - Tông Liên Hoa', 'skin', 'Nu', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nu/aocom_nu_lienhoa_1790757463452.jpg', 'Áo Cắm thiết kế truyền thống dành cho Nữ phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('aodai_nu_lienhoa_2', 'Áo Dài (Nữ) - Tông Liên Hoa', 'skin', 'Nu', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nu/aodai_nu_lienhoa_1790759989693.jpg', 'Áo Dài thiết kế truyền thống dành cho Nữ phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('aonamthan_nu_lienhoa_3', 'Áo Năm Thân (Nữ) - Tông Liên Hoa', 'skin', 'Nu', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nu/aonamthan_nu_lienhoa_1790759625186.jpg', 'Áo Năm Thân thiết kế truyền thống dành cho Nữ phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('aotac_nu_lienhoa_4', 'Áo Tấc Ngũ Thân (Nữ) - Tông Liên Hoa', 'skin', 'Nu', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nu/aotac_nu_lienhoa_1790759063827.jpg', 'Áo Tấc Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('daotien_nu_lienhoa_5', 'Trang Phục Dao Tiền (Nữ) - Tông Liên Hoa', 'skin', 'Nu', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nu/daotien_nu_lienhoa_1790760615650.jpg', 'Trang Phục Dao Tiền thiết kế truyền thống dành cho Nữ phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('hmong_nu_lienhoa_6', 'Trang Phục H''Mông (Nữ) - Tông Liên Hoa', 'skin', 'Nu', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nu/hmong_nu_lienhoa_1790761158808.jpg', 'Trang Phục H''Mông thiết kế truyền thống dành cho Nữ phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('nguthan_nu_lienhoa_7', 'Áo Ngũ Thân (Nữ) - Tông Liên Hoa', 'skin', 'Nu', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nu/nguthan_nu_lienhoa_1790758640760.jpg', 'Áo Ngũ Thân thiết kế truyền thống dành cho Nữ phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('nhatbinh_nu_lienhoa_8', 'Áo Nhật Bình (Nữ) - Tông Liên Hoa', 'skin', 'Nu', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nu/nhatbinh_nu_lienhoa_1790757854579.jpg', 'Áo Nhật Bình thiết kế truyền thống dành cho Nữ phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('tuthan_nu_lienhoa_9', 'Áo Tứ Thân (Nữ) - Tông Liên Hoa', 'skin', 'Nu', 'LienHoa', 'Liên Hoa', '/assets/images/system/Colors/LienHoa/Nu/tuthan_nu_lienhoa_1790759336128.jpg', 'Áo Tứ Thân thiết kế truyền thống dành cho Nữ phối tông màu Liên Hoa quý phái.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Dạ hội văn hóa"'::text[], '"Liên Hoa"'::text[]),
('quan_dui_nam_3', 'Quần Đũi Nam Cổ Truyền', 'pants', 'Nam', NULL, NULL, '/assets/images/system/Pants/quan_dui_nam_3.jpg', 'Chất liệu vải đũi mộc tự nhiên, thoáng mát, dáng suông truyền thống dành cho nam giới.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Sự kiện văn hóa"'::text[], '"Trắng","Đen","Mỡ Gà"'::text[]),
('quan_linh_nu_4', 'Quần Lĩnh Nữ Đen Óng', 'pants', 'Nữ', NULL, NULL, '/assets/images/system/Pants/quan_linh_nu_4.jpg', 'Chất liệu lụa lĩnh Bưởi màu đen tuyền bóng nhẹ, dệt thủ công quý phái cho nữ giới.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Sự kiện văn hóa"'::text[], '"Trắng","Đen","Mỡ Gà"'::text[]),
('quan_moga_nu_6', 'Quần Mỡ Gà Nữ Thướt Tha', 'pants', 'Nữ', NULL, NULL, '/assets/images/system/Pants/quan_moga_nu_6.jpg', 'Tông màu vàng mỡ gà ấm áp, chất lụa mềm mại tôn lên vẻ thướt tha của thiếu nữ.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Sự kiện văn hóa"'::text[], '"Trắng","Đen","Mỡ Gà"'::text[]),
('quan_phi_nu_5', 'Quần Phi Bóng Nữ Cung Đình', 'pants', 'Nữ', NULL, NULL, '/assets/images/system/Pants/quan_phi_nu_5.jpg', 'Vải phi bóng cao cấp ánh ngọc, thường dùng trong trang phục dạ yến chốn cung đình.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Sự kiện văn hóa"'::text[], '"Trắng","Đen","Mỡ Gà"'::text[]),
('quan_so_nam_1', 'Quần Sa Trắng Nam Nhã Nhặn', 'pants', 'Nam', NULL, NULL, '/assets/images/system/Pants/quan_so_nam_1.jpg', 'Vải sa dệt mỏng nhẹ sắc trắng tinh khôi, tạo dáng vẻ nho nhã, thanh cao của bậc nho sĩ.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Sự kiện văn hóa"'::text[], '"Trắng","Đen","Mỡ Gà"'::text[]),
('quan_trang_nam_2', 'Quần Lụa Trắng Nam Cổ Phong', 'pants', 'Nam', NULL, NULL, '/assets/images/system/Pants/quan_trang_nam_2.jpg', 'Lụa tơ tằm trắng ngà mềm mại, chuẩn mực phối cùng các dáng áo dài ngũ thân và áo tấc.', '"Lễ cưới cổ phong","Tết Nguyên Đán","Sự kiện văn hóa"'::text[], '"Trắng","Đen","Mỡ Gà"'::text[]),
('bo_3_vong_ximen_vang_19', 'Bộ 3 Vòng Ximen Vàng Cát Tường', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/bo_3_vong_ximen_vang_19.jpg', 'Bộ vòng tay ximen vàng chạm khắc tinh xảo, biểu trưng cho sự sung túc và may mắn.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('choker_lua_den_15', 'Kiềng Dải Lụa Đen Cổ Điển', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/choker_lua_den_15.jpg', 'Dải lụa đen mềm ôm sát cổ kết hợp mặt ngọc cổ truyền, điểm xuyết nét kiêu sa.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('day_chuyen_ngoc_boi_rong_13', 'Dây Chuyền Ngọc Bội Chạm Rồng', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/day_chuyen_ngoc_boi_rong_13.jpg', 'Mặt ngọc bích chạm hình rồng uy nghi, dây tết thủ công biểu thị phẩm cấp quyền quý.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('hoa_tai_ngoc_trai_7', 'Hoa Tai Ngọc Trai Quý Phái', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/hoa_tai_ngoc_trai_7.jpg', 'Ngọc trai nước ngọt trắng sáng tự nhiên, mang nét thanh lịch, đài các.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('hoa_tai_tua_rua_do_9', 'Hoa Tai Tua Rua Đỏ Cung Đình', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/hoa_tai_tua_rua_do_9.jpg', 'Sợi chỉ tơ đỏ thắm kết tua rua buông rủ, tạo điểm nhấn rạng ngời và may mắn.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('khan_dong_chu_nhan_nam_2', 'Khăn Đóng Chữ Nhan Nam Quý Tộc', 'accessory', 'Nam', NULL, NULL, '/assets/images/system/Accessories/khan_dong_chu_nhan_nam_2.jpg', 'Khăn đóng xếp nếp chữ Nhan chỉnh tề, biểu tượng cho phong thái chững chạc của nam tử.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('khuyen_tai_cam_thach_10', 'Khuyên Tai Cẩm Thạch Hoàng Cung', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/khuyen_tai_cam_thach_10.jpg', 'Ngọc cẩm thạch xanh ngọc bích mài nhẵn, toát lên nét quyền quý và trường thọ.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('khuyen_tai_hoa_sen_6', 'Khuyên Tai Hoa Sen Bạc Tinh Xảo', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/khuyen_tai_hoa_sen_6.jpg', 'Bạc ta đúc hình cánh hoa sen thanh khiết, biểu tượng quốc hoa Việt Nam.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('khuyen_tai_trong_dong_8', 'Khuyên Tai Họa Tiết Trống Đồng', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/khuyen_tai_trong_dong_8.jpg', 'Họa tiết chim Lạc và mặt trời Đông Sơn đúc nổi bằng đồng cổ tinh xảo.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('kieng_co_bac_tron_11', 'Kiềng Cổ Bạc Tròn Cổ Truyền', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/kieng_co_bac_tron_11.jpg', 'Kiềng bạc trơn uốn cong thanh thoát, phụ kiện không thể thiếu của phụ nữ Việt xưa.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('lac_tay_bac_xa_cu_17', 'Lắc Tay Bạc Khảm Xà Cừ', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/lac_tay_bac_xa_cu_17.jpg', 'Bạc chạm hoa văn cổ khảm vỏ xà cừ óng ánh ngũ sắc tinh vi.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('man_xep_lua_nu_1', 'Mấn Xếp Lụa Nữ Quý Phái', 'accessory', 'Nữ', NULL, NULL, '/assets/images/system/Accessories/man_xep_lua_nu_1.jpg', 'Mấn quấn bằng lụa tơ tằm nhiều tầng tỉ mỉ, tôn lên nét duyên dáng của người phụ nữ.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('nhan_ngoc_boc_bac_20', 'Nhẫn Ngọc Bích Bọc Bạc Tinh Xảo', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/nhan_ngoc_boc_bac_20.jpg', 'Mặt ngọc tự nhiên vân biếc bọc viền bạc chạm hoa văn kỷ hà.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('non_la_bai_tho_3', 'Nón Lá Dây Ngắn Cờ Đỏ Việt Nam', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/non_la_bai_tho_3.jpg', 'Nón lá truyền thống với dây quai ngắn gọn gàng, bề mặt mang sắc đỏ rực rỡ của lá cờ Việt Nam điểm xuyết ngôi sao vàng và hoa văn cổ truyền.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('non_quai_thao_5', 'Nón Quai Thao Quan Họ Kinh Bắc', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/non_quai_thao_5.jpg', 'Nón ba tầm quai thao dệt tơ tằm buông rủ, đậm đà văn hóa dân ca Quan họ.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('tram_phuong_hoang_4', 'Trâm Cài Tóc Phượng Hoàng Mạ Vàng', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/tram_phuong_hoang_4.jpg', 'Trâm cài tóc tạo hình chim phụng ngậm chuỗi ngọc mạ vàng rực rỡ chốn hoàng cung.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('vong_co_ngoc_trai_12', 'Vòng Cổ Ngọc Trai Hoàng Gia', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/vong_co_ngoc_trai_12.jpg', 'Chuỗi hạt ngọc trai tròn đều lấp lánh, biểu trưng cho sự viên mãn và vương giả.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('vong_co_tram_huong_14', 'Vòng Cổ Trầm Hương Vân Mây', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/vong_co_tram_huong_14.jpg', 'Hạt trầm hương rừng tự nhiên tỏa hương thơm thanh tịnh, mang lại bình an.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('vong_tay_ngoc_bich_16', 'Vòng Tay Ngọc Bích Cổ Phong', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/vong_tay_ngoc_bich_16.jpg', 'Vòng ngọc bích nguyên khối xanh thẳm, bóng mịn và mang vượng khí cát lành.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[]),
('vong_tay_tram_huong_vang_18', 'Vòng Tay Trầm Hương Bọc Vàng', 'accessory', 'Chung', NULL, NULL, '/assets/images/system/Accessories/vong_tay_tram_huong_vang_18.jpg', 'Hạt trầm hương quý bọc vàng 18k chạm khắc hoa văn triều Nguyễn sang trọng.', '"Lễ nghi truyền thống","Lễ hội","Dạ yến"'::text[], '"Vàng","Bạc","Ngọc Bích"'::text[])
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    gender = EXCLUDED.gender,
    "colorFolder" = EXCLUDED."colorFolder",
    "colorName" = EXCLUDED."colorName",
    image_filename = EXCLUDED.image_filename,
    description = EXCLUDED.description,
    suitable_events = EXCLUDED.suitable_events,
    recommended_colors = EXCLUDED.recommended_colors,
    updated_at = TIMEZONE('utc'::text, NOW());
